export const notificationsList = [
  {
    id: 1,
    icon: "../public/images/avatar-mark-webber.webp",
    name: "Mark Webber",
    action: "reacted to your recent post",
    event: "My first tournament today!",
    date: "1m ago",
  },
  {
    id: 2,
    icon: "../public/images/avatar-angela-gray.webp",
    name: "Angela Gray",
    action: "followed you",
    date: "5m ago",
  },
  {
    id: 3,
    icon: "../public/images/avatar-jacob-thompson.webp",
    name: "Jacob Thompson",
    action: "has joined your group",
    event: "Chess Club",
    date: "1 day ago",
  },
  {
    id: 4,
    icon: "../public/images/avatar-rizky-hasanuddin.webp",
    name: "Rizky Hasanuddin",
    action: "sent you a private message",

    date: "5 days ago",
  },
  {
    id: 5,
    icon: "../public/images/avatar-kimberly-smith.webp",
    name: "Kimberly Smith",
    action: "commented on your picture",
    eventImg: "../public/images/image-chess.webp",
    date: "1 week ago",
  },
  {
    id: 6,
    icon: "../public/images/avatar-nathan-peterson.webp",
    name: "Nathan Peterson",
    action: "reacted to your recent post",
    event: "5 end-game strategies to increase your win rate",
    date: "2 weeks ago",
  },
  {
    id: 7,
    icon: "../public/images/avatar-anna-kim.webp",
    name: "Anna Kim",
    action: "left the group",
    event: "Chess Club",
    date: "2 weeks ago",
  },
];
